<?xml version="1.0" encoding="UTF-8"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <!-- Material Definitions -->
    <gazebo reference="base_link">
        <material>Gazebo/Green</material>
    </gazebo>

    <gazebo reference="leftwheel_link">
        <material>Gazebo/Grey</material>
    </gazebo>

    <gazebo reference="rightwheel_link">
        <material>Gazebo/Grey</material>
    </gazebo>
    
    <gazebo reference="castorwheel_link">
        <material>Gazebo/Grey</material>
        <mu1 value="0.1" />
        <mu2 value="0.1" />
    </gazebo>

    <!-- Plugins Section -->

    <gazebo>
        <!-- <plugin
            filename="gz-sim-physics-system"
            name="gz::sim::systems::Physics">
        </plugin> -->
  
        <plugin
            filename="gz-sim-user-commands-system"
            name="gz::sim::systems::UserCommands">
        </plugin>
  
        <plugin
            filename="gz-sim-scene-broadcaster-system"
            name="gz::sim::systems::SceneBroadcaster">
        </plugin>
  
        <plugin
            filename="gz-sim-sensors-system"
            name="gz::sim::systems::Sensors">
            <render_engine>ogre2</render_engine>
        </plugin>
      
        <plugin
            filename="gz-sim-imu-system"
            name="gz::sim::systems::Imu">
        </plugin>

        <!-- Differential drive plugin -->
        <plugin
            filename="gz-sim-diff-drive-system"
            name="gz::sim::systems::DiffDrive">

            <!-- wheels -->
            <left_joint>base_leftwheel_joint</left_joint>
            <right_joint>base_rightwheel_joint</right_joint>

            <!-- kinematics -->
            <wheel_separation>${base_width + wheel_length}</wheel_separation>
            <wheel_radius>${wheel_radius}</wheel_radius> <!-- computed from <wheel_diameter> in the original plugin-->

            <!-- limits -->
            <!--<max_linear_acceleration>0.033</max_linear_acceleration> computed from <max_linear_acceleration> in the original plugin-->

            <topic>cmd_vel</topic> <!-- from <command_topic> -->

            <odom_topic>odom</odom_topic> <!-- from <odometry_topic> -->
            <frame_id>odom</frame_id> <!-- from <odometry_frame> -->
            <child_frame_id>base_footprint</child_frame_id> <!-- from <robot_base_frame> -->
            <odom_publisher_frequency>50</odom_publisher_frequency> <!-- from <update_rate>-->

            <tf_topic>/tf</tf_topic> <!-- Short topic name for tf output -->
        </plugin>

        <plugin filename="gz-sim-joint-state-publisher-system"
            name="gz::sim::systems::JointStatePublisher">
            <topic>joint_states</topic> <!--from <ros><remapping> -->
            <joint_name>base_leftwheel_joint</joint_name>
            <joint_name>base_rightwheel_joint</joint_name>
        </plugin>

    </gazebo>

</robot>
